name: Build and Publish APK

on:
  push:
    branches:
      - section_two_app_structure  # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build APK
        run: ./gradlew assembleDebug



      - name: Upload APK to App Center
        uses: MSAppCenter/appcenter-upload-action@v1
        with:
          app_name: 'BuildExample' # Replace with your App Center app name
          app_owner_name: 'Qenawi' # Replace with your App Center owner name
          token: ${{ secrets.APPCENTER_APP_SECRET }} # Store your App Center token in GitHub secrets
          file: app/build/outputs/apk/debug/app-debug.apk # Replace with your APK path

